# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  api_key = app_store_connect_api_key(
    key_id: "7NQ9QVS88N",
    issuer_id: "2bdcfde8-ccdd-4138-94a1-9b4a61ca45e4",
    key_filepath: "./AuthKey_7NQ9QVS88N.p8",
    duration: 1200,
    in_house: false
  )

  desc "Push a new beta build to TestFlight"
  lane :beta do

    current_build_num = app_store_build_number(
      api_key: api_key,
      live: false,
      version: "1.0",
      initial_build_number: 0
    )

    increment_build_number(xcodeproj: "Silo.xcodeproj", build_number: current_build_num + 1)
    build_app(workspace: "Silo.xcworkspace", scheme: "Silo")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
