import { COLOR, THEME } from 'native-x-theme'

export enum COLOR_X {
  ACCENT1 = 'ACCENT1',
  ACCENT2 = 'ACCENT2',
  ACCENT3 = 'ACCENT3',
  ACCENT4 = 'ACCENT4',
  ACCENT5 = 'ACCENT5',
  ACCENT_LIGHT = 'ACCENT_LIGHT',
  SUCCESS_LIGHT = 'SUCCESS_LIGHT',
  ERROR_LIGHT = 'ERROR_LIGHT',
  WARNING_LIGHT = 'WARNING_LIGHT',
  TERTIARY_DARK = 'TERTIARY_DARK',
  PLACEHOLDER = 'PLACEHOLDER',
  PAGE = 'PAGE',
}

export const THEMES = {
  [THEME.LIGHT]: {
    [COLOR.PRIMARY]: '#FFFFFF',
    [COLOR.SECONDARY]: '#235039',
    [COLOR.TERTIARY]: '#8492A6',
    [COLOR.ACCENT]: '#3C69C3',
    [COLOR_X.ACCENT_LIGHT]: '#DEEAF8',
    [COLOR.DIVIDER]: '#F7F7F7',
    [COLOR.DISABLED]: '#EEEEEE',
    [COLOR.INPUT]: '#EEEEEE',
    [COLOR.SUCCESS]: '#20923E',
    [COLOR_X.SUCCESS_LIGHT]: '#EBF9EE',
    [COLOR.ERROR]: '#FF3B30',
    [COLOR_X.ERROR_LIGHT]: '#FFEBEA',
    [COLOR.WARNING]: '#FFA100',
    [COLOR_X.WARNING_LIGHT]: '#FFF4E6',
    [COLOR.TRANSPARENT]: 'transparent',
    [COLOR_X.ACCENT1]: '#15A569',
    [COLOR_X.ACCENT2]: '#6C8A7B',
    [COLOR_X.ACCENT3]: '#0A3C23',
    [COLOR_X.PLACEHOLDER]: '#FFFFFF50',
    [COLOR_X.PAGE]: '#EFF2F7',
    [COLOR_X.ACCENT4]: '#EDAB4D',
    [COLOR_X.ACCENT5]: '#061A40',
  },
}
